config/routes.rb
Rails.application.routes.draw do
#   devise_for :employees  , :skip => [:registrations] 
# as :employees do
#   get 'employees/edit' => 'devise/registrations#edit', :as => 'edit_employee_registration'
#   put 'employees' => 'devise/registrations#update', :as => 'employee_registration'
# end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  
    root to: "home#index"
  
    # devise_for :employees, controllers: {
    #   sessions: 'employees/sessions',
    #   registrations: 'employees/registrations',
    #   passwords: 'employees/passwords'
    # }

    devise_for :employees,
    controllers: {
         sessions: 'employees/sessions',
         invitations: 'employees/invitations',
         passwords: 'employees/passwords'
    },
    :skip => [:registrations] 
  as :employee do
  get 'employees/:id' => 'employees/registrations#index', :as => 'employees_index'
  get 'employees/edit/:id' => 'employees/registrations#edit', :as => 'edit_employee_registration'
  get 'employees/edit/:id/change_password' => 'employees/registrations#edit_password', :as => 'edit_employee_registration_password'
  put 'employees' => 'employees/registrations#update', :as => 'employee_registration'
  end

  # routes for divisions controller
  get 'divisions' => 'divisions#index', :as => 'divisions_index'
  get 'divisions/show/:id' => 'divisions#show', :as => 'divisions_show'
  post 'divisions' => 'divisions#create'
  get 'divisions/new' => 'divisions#new', :as => 'new_division'
  delete 'divisions/:id/delete' => 'divisions#destroy', as: 'divisions_delete'
  get '/divisions/:id/edit' => 'divisions#edit', as: 'divisions_edit'
  patch  '/divisions/:id' => 'divisions#update', as: 'update_division'
  put   '/divisions/:id' => 'divisions#update'
  get '/divisions/:id/delete' => 'divisions#destroy'
 

  # routes for projects controller

  get 'projects' => 'projects#index', as: 'projects_index'
  get 'projects/new' => 'projects#new', as: 'new_projects'
  get 'projects/:id' => 'projects#show', as: 'projects_show'
  post 'projects/create' => 'projects#create', as: 'projects'

   # routes for project_assignment controller

   post 'project_assignmnet/assign_project' => 'project_assignments#assign_project'
   delete '/projects/:project_id/:id' => 'project_assignments#destroy', as: 'project_assignment_delete'

   # profile controller for employee

   get 'my_profile', to: 'profiles#profile', as: 'my_profile'
   get 'profile/change_photo' => 'profiles#change_photo'
   patch 'profile/change_photo' => 'profiles#update_photo'
   get 'profile/edit_password' => 'profiles#edit_password'
   patch 'profile/update_password' => 'profiles#update_password'


  # resource :profile, only: [:edit] do
  #   collection do
  #     get 'edit_password'
  #     patch 'update_password'
  #   end
  #end

 


end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
    before_action :authenticate_employee!

    def profile
        
    end

    def change_photo
      @employee = current_employee
    end

    def edit_password
        @employee = current_employee
    end

    def update_photo
      @employee = current_employee
      if @employee.update(params.require(:employee).permit(:image))
        redirect_to root_path
      else
        render "change_photo"
      end

    end
  
    def update_password
        @employee = current_employee
      if @employee.update_with_password(employee_params)
        
        # Sign in the user by passing validation in case their password changed
        bypass_sign_in(@employee)
        redirect_to root_path
      else
        render "edit_password"
      end
    end

  
    private
  
    def employee_params
      params.require(:employee).permit(:password, :password_confirmation, :current_password)
    end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/change_photo.html.erb
<h2>Change Profile Picture</h2>

<%= form_for(@employee, :url => {:action => "update_photo" } ) do |f| %>

    <div class="field">
    <%= f.file_field :image %>
    </div>

   <div class="actions">
    <%= f.submit "Update" %>
  </div>
<% end %>

app/views/profiles/edit_password.html.erb
<%= form_for(@employee, :url => { :action => "update_password" } ) do |f| %>
  <div class="field">
    <%= f.label :password, "Password" %><br />
    <%= f.password_field :password, :autocomplete => "off"  %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
   <div class="field">
    <%= f.label :current_password %> <i>(we need your current password to confirm your changes)</i><br />
    <%= f.password_field :current_password %>
  </div>
  <div class="action_container">
    <%= f.submit %>
  </div>
<% end %>

app/views/profiles/profile.html.erb
<h1>My Profile</h1>
<table class="table" style="text-align:left;">
    <p><%=link_to "Change Password",profile_edit_password_path%></p>
    <% if current_employee.image.attached?%>
    <tr>
        <td><%= image_tag current_employee.image.variant(resize_to_limit: [100, 100]) %>
            <span><p><%=link_to "Change Profile Photo",profile_change_photo_path%></p></span>
         </td>
    </tr>
    <% else%>
     <tr>
        <td>
     <span><p><%=link_to "Add Profile Photo",profile_change_photo_path%></p></span>
    <%end%>
    </td>
    </tr>
    <tr>
        <td><b> Username :</b> <%= current_employee.username%></td>
    </tr>
    <tr>
        <td><b>Name :</b> <%= current_employee.name%></td>
    </tr>
    <tr>
        <td><b>Email :</b> <%= current_employee.email%></td>
    </tr>
</table>
<button type="button" class="btn btn-primary"><%= link_to "Back", :back , class:"btn" %></button>