config/routes.rb
Rails.application.routes.draw do
#   devise_for :employees  , :skip => [:registrations] 
# as :employees do
#   get 'employees/edit' => 'devise/registrations#edit', :as => 'edit_employee_registration'
#   put 'employees' => 'devise/registrations#update', :as => 'employee_registration'
# end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  
    root to: "home#index"
  
    # devise_for :employees, controllers: {
    #   sessions: 'employees/sessions',
    #   registrations: 'employees/registrations',
    #   passwords: 'employees/passwords'
    # }

    devise_for :employees,
    controllers: {
         sessions: 'employees/sessions',
         invitations: 'employees/invitations',
         passwords: 'employees/passwords'
    },
    :skip => [:registrations] 
  as :employee do
  get 'employees/:id' => 'employees/registrations#index', :as => 'employees_index'
  get 'employees/edit/:id' => 'employees/registrations#edit', :as => 'edit_employee_registration'
  get 'employees/edit/:id/change_password' => 'employees/registrations#edit_password', :as => 'edit_employee_registration_password'
  put 'employees' => 'employees/registrations#update', :as => 'employee_registration'
  end

  # routes for divisions controller
  get 'divisions' => 'divisions#index', :as => 'divisions_index'
  get 'divisions/show/:id' => 'divisions#show', :as => 'divisions_show'
  post 'divisions' => 'divisions#create'
  get 'divisions/new' => 'divisions#new', :as => 'new_division'
  delete 'divisions/:id/delete' => 'divisions#destroy', as: 'divisions_delete'
  get '/divisions/:id/edit' => 'divisions#edit', as: 'divisions_edit'
  patch  '/divisions/:id' => 'divisions#update', as: 'update_division'
  put   '/divisions/:id' => 'divisions#update'
  get '/divisions/:id/delete' => 'divisions#destroy'
 

  # routes for projects controller

  get 'projects' => 'projects#index', as: 'projects_index'
  get 'projects/new' => 'projects#new', as: 'new_projects'
  get 'projects/:id' => 'projects#show', as: 'projects_show'
  post 'projects/create' => 'projects#create', as: 'projects'

   # routes for project_assignment controller

   post 'project_assignmnet/assign_project' => 'project_assignments#assign_project'
   delete '/projects/:project_id/:id' => 'project_assignments#destroy', as: 'project_assignment_delete'

   # profile controller for employee

   get 'my_profile', to: 'profiles#profile', as: 'my_profile'
   get 'profile/change_photo' => 'profiles#change_photo'
   patch 'profile/change_photo' => 'profiles#update_photo'
   get 'profile/edit_password' => 'profiles#edit_password'
   patch 'profile/update_password' => 'profiles#update_password'


  # resource :profile, only: [:edit] do
  #   collection do
  #     get 'edit_password'
  #     patch 'update_password'
  #   end
  #end

 


end

app/models/division.rb
class Division < ApplicationRecord
    has_many :employees, dependent: :nullify

    validates :name, length: { minimum: 2, maximum: 20}, presence: true, uniqueness: true



end

app/controllers/divisions_controller.rb
class DivisionsController < ApplicationController
    before_action :set_division, only: [:show, :edit, :update, :destroy]
    before_action :authenticate_employee!
    before_action :is_hr_manager?

    def index

        @division= Division.all

    end

    def show
       
    end

    def new 

        @division = Division.new

    end

    def create

        @division = Division.create(division_params)
       if @division.save
            flash[:alert] = "Division Created"
            redirect_to divisions_index_path
       else 
            render "new" , status: :unprocessable_entity
       end
  
    end

    def edit
        
    end

    def update
        
        if @division.update(division_params)
        flash[:alert] = "Division Updated"
        redirect_to divisions_index_path
        else

            redirect_to divisions_edit_path(@division.id)
            flash[:alert] = "Enter Valid Division Name"
        end

    end

    def destroy
        
        @division.destroy
        redirect_to divisions_index_path
    
    end
    
private

    def is_hr_manager?

        redirect_to root_path unless current_employee.hr_manager
    end

    def set_division

        @division= Division.find(params[:id])

    end

    def division_params

        params.require(:division).permit(:name)

    end



end

app/helpers/divisions_helper.rb
module DivisionsHelper
end

app/views/divisions/edit.html.erb
<div>
    <h2>Update Division</h2> <br/>

    <%= form_with(model: @division, url:update_division_path) do |f| %> 
          <ul>
            <% @division.errors.full_messages.each do |error| %>
            <li class="error-message"><%= error %></li>
            <% end %>
        </ul>

        <%= f.label :name %>
        <%= f.text_field :name %> <br/>
        <%= f.submit %> <br/>
    <% end %>
</div>
<button type="button" class="btn btn-primary"><%= link_to "Back", :back , class:"btn" %></button>

app/views/divisions/index.html.erb
<h2> List of Divisions </h2>

<table class="table" style="text-align:left;">
    <tr>
        <th> Division Name</th>
    </tr>
    <% @division.each do |d| %>
    <tr>
        <td><%= link_to "#{d.name}",divisions_show_path(d.id)%></td>

        <td><%= link_to "Edit",divisions_edit_path(d.id)%></td>

        <td> <%= link_to "Delete", divisions_delete_path(d.id),
                method: :delete,
                data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' } %>
        </td>

    <% end %> 
    </tr>
</table>
<button type="button" class="btn btn-primary"><%= link_to "Back", :back , class:"btn" %></button>

app/views/divisions/new.html.erb
<div>
    <h2>Create New Division</h2> <br/>

    <%= form_with(model: @division) do |f| %> 
        <ul>
            <% @division.errors.full_messages.each do |error| %>
            <li class="error-message"><%= error %></li>
            <% end %>
        </ul>
        <%= f.label :name %>
        <%= f.text_field :name %> <br/>
        <%= f.submit %> <br/>
    <% end %>
</div>
<button type="button" class="btn btn-primary"><%= link_to "Back", :back , class:"btn" %></button>

app/views/divisions/show.html.erb
<h3>Department : <%= @division.name %></h3>
<%@division.employees.each do |e|%>
<p>Employee Name : <%= e.name%></p> </br>
<%end%>
<button type="button" class="btn btn-primary"><%= link_to "Back", :back , class:"btn" %></button>