config/routes.rb
Rails.application.routes.draw do
#   devise_for :employees  , :skip => [:registrations] 
# as :employees do
#   get 'employees/edit' => 'devise/registrations#edit', :as => 'edit_employee_registration'
#   put 'employees' => 'devise/registrations#update', :as => 'employee_registration'
# end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  
    root to: "home#index"
  
    # devise_for :employees, controllers: {
    #   sessions: 'employees/sessions',
    #   registrations: 'employees/registrations',
    #   passwords: 'employees/passwords'
    # }

    devise_for :employees,
    controllers: {
         sessions: 'employees/sessions',
         invitations: 'employees/invitations',
         passwords: 'employees/passwords'
    },
    :skip => [:registrations] 
  as :employee do
  get 'employees/:id' => 'employees/registrations#index', :as => 'employees_index'
  get 'employees/edit/:id' => 'employees/registrations#edit', :as => 'edit_employee_registration'
  get 'employees/edit/:id/change_password' => 'employees/registrations#edit_password', :as => 'edit_employee_registration_password'
  put 'employees' => 'employees/registrations#update', :as => 'employee_registration'
  end

  # routes for divisions controller
  get 'divisions' => 'divisions#index', :as => 'divisions_index'
  get 'divisions/show/:id' => 'divisions#show', :as => 'divisions_show'
  post 'divisions' => 'divisions#create'
  get 'divisions/new' => 'divisions#new', :as => 'new_division'
  delete 'divisions/:id/delete' => 'divisions#destroy', as: 'divisions_delete'
  get '/divisions/:id/edit' => 'divisions#edit', as: 'divisions_edit'
  patch  '/divisions/:id' => 'divisions#update', as: 'update_division'
  put   '/divisions/:id' => 'divisions#update'
  get '/divisions/:id/delete' => 'divisions#destroy'
 

  # routes for projects controller

  get 'projects' => 'projects#index', as: 'projects_index'
  get 'projects/new' => 'projects#new', as: 'new_projects'
  get 'projects/:id' => 'projects#show', as: 'projects_show'
  post 'projects/create' => 'projects#create', as: 'projects'

   # routes for project_assignment controller

   post 'project_assignmnet/assign_project' => 'project_assignments#assign_project'
   delete '/projects/:project_id/:id' => 'project_assignments#destroy', as: 'project_assignment_delete'

   # profile controller for employee

   get 'my_profile', to: 'profiles#profile', as: 'my_profile'
   get 'profile/change_photo' => 'profiles#change_photo'
   patch 'profile/change_photo' => 'profiles#update_photo'
   get 'profile/edit_password' => 'profiles#edit_password'
   patch 'profile/update_password' => 'profiles#update_password'


  # resource :profile, only: [:edit] do
  #   collection do
  #     get 'edit_password'
  #     patch 'update_password'
  #   end
  #end

 


end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    before_action :authenticate_employee!

    #root 
    def index
        
    end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_employee.html.erb
        <h4>Assigned Project<h4>
        <% emp.projects.each do |p| %>
        <%=link_to p.name,  projects_show_path(p.id) %>
        <% end %>

app/views/home/_hr_manager.html.erb
  
        <div class="hr-manager-dasboard-btn-1">
            <%=link_to "Divisions", divisions_index_path, class: "hr-manager-dasboard-btn"%>
            <%=link_to "Add New Division", new_division_path, class: "hr-manager-dasboard-btn" %>
        </div>
    </div>

        <div class="hr-manager-dasboard-btn-2">
            <%=link_to "Employees", employees_index_path(:id =>"0"), class: "hr-manager-dasboard-btn" %>
           <%=link_to "Add New Employee", new_employee_invitation_path, class: "hr-manager-dasboard-btn"%>
        </div>

 

app/views/home/_project_manager.html.erb
        <%=link_to "Projects", projects_index_path %> </br>
        <%=link_to "Employees", employees_index_path(id:0) %> </br>
        <%=link_to "Add New Projects", new_projects_path %></br>

app/views/home/index.html.erb
<div class="home-dashboard">
  
    <% if current_employee %>
        <div class="employee-session-profile">
        <%= link_to "My Profile", my_profile_path, type:"button", class:"btn btn-primary" %> <br/><br/>
        </div>

        <div class="session-logout">
        <%=button_to(
        "Log Out",
        destroy_employee_session_path,
        method: :delete)%> 
        </div>

      <table class="table" style="text-align:left;">
    
          <% if current_employee.hr_manager %>
              
              <div class="hr-dashboard">
                <h1>Dashboard<span>HR Manager</span></h1>
              </div>
          <%= render 'hr_manager' %>
      
          <% elsif current_employee.project_manager%>
      
              <div class="hr-dashboard">
                <h1>Dashboard<span>Project Manager</span></h1>
              </div>
          <%= render 'project_manager' %>
            
          <% else %>
          
                <div class="hr-dashboard">
                <h1>Dashboard<span>Employee</span></h1>
                </div>
           <%= render partial: 'employee', locals: {emp: current_employee } %>
          <% end %>

      <% else %>
      <%=link_to "Sign In", new_employee_session_path %>
      <% end %>
    </table>
    <marquee width="60%" direction="right" height="100px"><p style="color:red;">Under Development </p></marquee>
</div> 