config/routes.rb
Rails.application.routes.draw do
#   devise_for :employees  , :skip => [:registrations] 
# as :employees do
#   get 'employees/edit' => 'devise/registrations#edit', :as => 'edit_employee_registration'
#   put 'employees' => 'devise/registrations#update', :as => 'employee_registration'
# end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  
    root to: "home#index"
  
    # devise_for :employees, controllers: {
    #   sessions: 'employees/sessions',
    #   registrations: 'employees/registrations',
    #   passwords: 'employees/passwords'
    # }

    devise_for :employees,
    controllers: {
         sessions: 'employees/sessions',
         invitations: 'employees/invitations',
         passwords: 'employees/passwords'
    },
    :skip => [:registrations] 
  as :employee do
  get 'employees/:id' => 'employees/registrations#index', :as => 'employees_index'
  get 'employees/edit/:id' => 'employees/registrations#edit', :as => 'edit_employee_registration'
  get 'employees/edit/:id/change_password' => 'employees/registrations#edit_password', :as => 'edit_employee_registration_password'
  put 'employees' => 'employees/registrations#update', :as => 'employee_registration'
  end

  # routes for divisions controller
  get 'divisions' => 'divisions#index', :as => 'divisions_index'
  get 'divisions/show/:id' => 'divisions#show', :as => 'divisions_show'
  post 'divisions' => 'divisions#create'
  get 'divisions/new' => 'divisions#new', :as => 'new_division'
  delete 'divisions/:id/delete' => 'divisions#destroy', as: 'divisions_delete'
  get '/divisions/:id/edit' => 'divisions#edit', as: 'divisions_edit'
  patch  '/divisions/:id' => 'divisions#update', as: 'update_division'
  put   '/divisions/:id' => 'divisions#update'
  get '/divisions/:id/delete' => 'divisions#destroy'
 

  # routes for projects controller

  get 'projects' => 'projects#index', as: 'projects_index'
  get 'projects/new' => 'projects#new', as: 'new_projects'
  get 'projects/:id' => 'projects#show', as: 'projects_show'
  post 'projects/create' => 'projects#create', as: 'projects'

   # routes for project_assignment controller

   post 'project_assignmnet/assign_project' => 'project_assignments#assign_project'
   delete '/projects/:project_id/:id' => 'project_assignments#destroy', as: 'project_assignment_delete'

   # profile controller for employee

   get 'my_profile', to: 'profiles#profile', as: 'my_profile'
   get 'profile/change_photo' => 'profiles#change_photo'
   patch 'profile/change_photo' => 'profiles#update_photo'
   get 'profile/edit_password' => 'profiles#edit_password'
   patch 'profile/update_password' => 'profiles#update_password'


  # resource :profile, only: [:edit] do
  #   collection do
  #     get 'edit_password'
  #     patch 'update_password'
  #   end
  #end

 


end

app/models/project.rb
class Project < ApplicationRecord
    has_many :project_assignments
    has_many :employees, through: :project_assignments, dependent: :destroy

    validates :name, length: { minimum: 2}, presence: true
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
    before_action :authenticate_employee!
    before_action :is_project_manager? , except: [:index, :show]

    def index
        @project = Project.all
    end

    def show
        @project = Project.find(params[:id])
    end

    def new
        @project = Project.new
    end

    def create
        
        @project = Project.create(params.require(:project).permit(:name))
      

        if @project.save
            redirect_to projects_index_path
        else
            render "new" , status: :unprocessable_entity
        end

    end

    private

    def is_project_manager?
        redirect_to root_path unless current_employee.project_manager
    end


    

end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/index.html.erb
<h3>List of Projects </h3>
<h5>Project Name : <% @project.each do |p| %> </h5>
<%=link_to "#{p.id}, #{p.name}", projects_show_path(p.id)%><br/>
<% end %>
<button type="button" class="btn btn-primary"><%= link_to "Back", :back , class:"btn" %></button>

app/views/projects/new.html.erb
<div>
    <h2>Create New Projects</h2> <br/>

    <%= form_with(model: @project) do |f| %> 
        <%= f.label :name %>
        <%= f.text_field :name %> <br/>
        <%= f.submit %> <br/>
    <% end %>
</div>
<button type="button" class="btn btn-primary"><%= link_to "Back", :back , class:"btn" %></button>

app/views/projects/show.html.erb
<h4>Project Name : <%= @project.name%></h4>
<p>Employee Name : </p>
<% @project.employees.each do |e| %>
<%project_id=@project.id%>
<%= "+ #{e.name}" %> <br/>
    <% if current_employee.project_manager%>
    <%= button_to "Remove", project_assignment_delete_path(project_id, e.id),
                    method: :delete,
                    data: {confirm: 'Are you sure?' } %>  <br/>
    <% end %>
<% end %>
<button type="button" class="btn btn-primary"><%= link_to "Back", :back , class:"btn" %></button>